[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
modelmark = "modelmark.modelmark:run"

[project]
name = "modelmark"
version = "0.1.2"
description = "Benchmark framework for neural network models"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }

authors = [
    { name = "Andrew Larin" }
]

dependencies = [
    "numpy>=2.4",
    "pandas>=3.0",
	"torch>=2.12",
	"tqdm>=4.67",
	"playwright>=1.62",
	"rich>=15.0",
	"thop>=0.1"
]

[tool.setuptools.packages.find]
where = ["src"]